### ISSUE TITLE
Initial background color

### ISSUE THREAD

**Issue by TeemuSuoranta** [superevilmegaco/super-evil-new-tab-redux#1]
Hi!

I like to use dark background in my setup (have some stoic quotes in my setup https://github.com/TeemuSuoranta/chrome-new-tab-stoic-quotes). The old extension had one more configuration field for initial background color to avoid blinking as without it screen blinks often in white before stylesheet is loaded.

Is this something that could be added here or are there other ways to avoid blinking?

PS. I noticed that the default stylesheet is a bit different than with the old extension but that only requires some fine tuning in CSS so that's fine. Thank you for remaking this extension.

**Comment by walialu** [comment]
@TeemuSuoranta, I'll try to look into this :)

**Comment by walialu** [comment]
@TeemuSuoranta, I've submitted version 0.0.5 for review in the chrome webstore. Once it got approved and you have updated, you should see another option "background-color" in the options page.

**Comment by walialu** [comment]
Should be live by now :+1:

**Comment by TeemuSuoranta** [comment]
Thank you very much! With this addition super-evil-new-tab-redux should have all the same features as the original addition. I'll update my configuration repository and link to this add-on, too.
